title: <p align="center"><strong>WELCOME TO MY PORTFOLIO</strong></p>
logo: /assets/img/PARA_EL_PERFIL.JPG
description: Explore my journey, projects, and insights in Data Science, Analytics & Sustainability
theme: jekyll-theme-slate
